spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
  application:
    name: book-social-network-api
springdoc:
  default-produces-media-type: application/json
server:
  servlet:
    context-path: /api/v1
  port: 8080